## Manifiesto de despliegie
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demostracion
  labels:
    app: demostracion
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demostracion
  template:
    metadata:
      labels:
        app: demostracion
    spec:
      containers:
        - name: "demostracion"
          image: "116933114869.dkr.ecr.us-east-1.amazonaws.com/demostracion"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
