apiVersion: v1
kind: Service
metadata:
  name: demostracion-service
  labels:
    app: demostracion
spec:
  selector:
    app: demostracion
  ports:
    - name: http
      protocol: TCP
      port: 30500
      nodePort: 30500
      targetPort: 30500
    - name: https
      protocol: TCP
      port: 32500
      nodePort: 32500
      targetPort: 32500
  type: NodePort
